# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'dealerslist' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for dealerslist
  pod 'AppCenter/Crashes', '~> 1.1.0'
  pod 'AppCenter/Analytics', '~> 1.1.0'
  pod 'AppCenterReactNativeShared', '~> 1.1.0'


target "AppCenter" do
    
end


  target 'dealerslist-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'dealerslistTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'dealerslist-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for dealerslist-tvOS

  target 'dealerslist-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end


end
